#!/bin/bash
REMOTE_UPTIMECHECKER_PATH=/home/pi/UptimeChecker/
SSH_TARGET=raspi

scp .env $SSH_TARGET:$REMOTE_UPTIMECHECKER_PATH
scp index.js $SSH_TARGET:$REMOTE_UPTIMECHECKER_PATH
scp package.json $SSH_TARGET:$REMOTE_UPTIMECHECKER_PATH
scp package-lock.json $SSH_TARGET:$REMOTE_UPTIMECHECKER_PATH
scp status.json $SSH_TARGET:$REMOTE_UPTIMECHECKER_PATH

ssh raspi "cd $REMOTE_UPTIMECHECKER_PATH; npm i"
